# Air configuration for hot-reloading WITH DELVE DEBUGGER
# Use this when you need to attach a debugger
# Usage: air -c .air.debug.toml

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -gcflags 'all=-N -l' -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "migrations", "docs", "scripts", ".git", ".github", "bin"]
  exclude_file = []
  exclude_regex = ["_test.go", "_mock.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv exec ./tmp/main --listen=:2345 --headless=true --api-version=2 --accept-multiclient --continue --log"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "proto"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
