# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags: []
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck        # Check error returns
    - gosimple        # Simplify code
    - govet           # Reports suspicious constructs
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Static analysis
    - unused          # Detect unused code
    - gofmt           # Check formatting
    - goimports       # Check imports (with sorting!)
    - misspell        # Spell checking
    - stylecheck      # Style checking
    - gosec           # Security issues
    - revive          # Fast, extensible linter
    - unconvert       # Remove unnecessary conversions
    - unparam         # Unused function parameters
    - goconst         # Repeated strings
    - gocyclo         # Cyclomatic complexity
    - dupl            # Code duplication

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      # Allow not checking some safe operations
      - (io.Closer).Close

  goimports:
    # Put imports beginning with prefix after 3rd-party packages
    local-prefixes: github.com/company/order-delivery-service

  gosec:
    excludes:
      - G115  # Disable integer overflow warnings (we handle these explicitly)
    confidence: medium

  misspell:
    locale: US
    ignore-words:
      - cancelled  # British spelling used in proto

  stylecheck:
    checks: ["all", "-ST1003"]  # All checks except CamelCase names

  revive:
    confidence: 0.8

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  uniq-by-line: true
  exclude-rules:
    # Exclude specific linters for specific paths
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl

    # Exclude generated files
    - path: \.pb\.go$
      linters:
        - all

    # Ignore package comment warnings (we'll add them manually)
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
        - revive

    # Ignore CANCELLED misspelling (proto uses British spelling)
    - text: "`CANCELLED` is a misspelling of `CANCELED`"
      linters:
        - misspell

    # Allow defer log.Sync() without checking error in main
    - path: cmd/server/main\.go
      text: "Error return value of `log.Sync` is not checked"
      linters:
        - errcheck

    # Allow ReadHeaderTimeout for metrics server (it's internal only)
    - path: cmd/server/main\.go
      text: "G112: Potential Slowloris Attack"
      linters:
        - gosec

    # Allow int64 to int32 conversions in specific files (we validate bounds)
    - path: (grpc_handler|repository)\.go
      text: "G115: integer overflow conversion"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
