// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/delivery.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliveryStatus represents the current status of a delivery
type DeliveryStatus int32

const (
	// Unspecified (default)
	DeliveryStatus_UNSPECIFIED DeliveryStatus = 0
	// Pending - awaiting driver assignment
	DeliveryStatus_PENDING DeliveryStatus = 1
	// Assigned - driver assigned
	DeliveryStatus_ASSIGNED DeliveryStatus = 2
	// Picked up - package collected
	DeliveryStatus_PICKED_UP DeliveryStatus = 3
	// In transit - on the way
	DeliveryStatus_IN_TRANSIT DeliveryStatus = 4
	// Delivered - successfully delivered
	DeliveryStatus_DELIVERED DeliveryStatus = 5
	// Failed - delivery failed
	DeliveryStatus_FAILED DeliveryStatus = 6
	// Cancelled - delivery cancelled
	DeliveryStatus_CANCELLED DeliveryStatus = 7
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PENDING",
		2: "ASSIGNED",
		3: "PICKED_UP",
		4: "IN_TRANSIT",
		5: "DELIVERED",
		6: "FAILED",
		7: "CANCELLED",
	}
	DeliveryStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"PENDING":     1,
		"ASSIGNED":    2,
		"PICKED_UP":   3,
		"IN_TRANSIT":  4,
		"DELIVERED":   5,
		"FAILED":      6,
		"CANCELLED":   7,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_delivery_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_proto_delivery_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{0}
}

// Address represents a physical address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// DeliveryAssignment represents a delivery assignment
type DeliveryAssignment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId               string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId              string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status                DeliveryStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=delivery.DeliveryStatus" json:"status,omitempty"`
	PickupAddress         *Address               `protobuf:"bytes,5,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress       *Address               `protobuf:"bytes,6,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	ScheduledPickupTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scheduled_pickup_time,json=scheduledPickupTime,proto3" json:"scheduled_pickup_time,omitempty"`
	EstimatedDeliveryTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=estimated_delivery_time,json=estimatedDeliveryTime,proto3" json:"estimated_delivery_time,omitempty"`
	ActualPickupTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=actual_pickup_time,json=actualPickupTime,proto3" json:"actual_pickup_time,omitempty"`
	ActualDeliveryTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=actual_delivery_time,json=actualDeliveryTime,proto3" json:"actual_delivery_time,omitempty"`
	Notes                 string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeliveryAssignment) Reset() {
	*x = DeliveryAssignment{}
	mi := &file_proto_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAssignment) ProtoMessage() {}

func (x *DeliveryAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAssignment.ProtoReflect.Descriptor instead.
func (*DeliveryAssignment) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryAssignment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeliveryAssignment) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DeliveryAssignment) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_UNSPECIFIED
}

func (x *DeliveryAssignment) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *DeliveryAssignment) GetDeliveryAddress() *Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *DeliveryAssignment) GetScheduledPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledPickupTime
	}
	return nil
}

func (x *DeliveryAssignment) GetEstimatedDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return nil
}

func (x *DeliveryAssignment) GetActualPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualPickupTime
	}
	return nil
}

func (x *DeliveryAssignment) GetActualDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualDeliveryTime
	}
	return nil
}

func (x *DeliveryAssignment) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *DeliveryAssignment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeliveryAssignment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateDeliveryAssignmentRequest creates a new delivery assignment
type CreateDeliveryAssignmentRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrderId               string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PickupAddress         *Address               `protobuf:"bytes,2,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress       *Address               `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	ScheduledPickupTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_pickup_time,json=scheduledPickupTime,proto3" json:"scheduled_pickup_time,omitempty"`
	EstimatedDeliveryTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=estimated_delivery_time,json=estimatedDeliveryTime,proto3" json:"estimated_delivery_time,omitempty"`
	Notes                 string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateDeliveryAssignmentRequest) Reset() {
	*x = CreateDeliveryAssignmentRequest{}
	mi := &file_proto_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryAssignmentRequest) ProtoMessage() {}

func (x *CreateDeliveryAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryAssignmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeliveryAssignmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateDeliveryAssignmentRequest) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *CreateDeliveryAssignmentRequest) GetDeliveryAddress() *Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *CreateDeliveryAssignmentRequest) GetScheduledPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledPickupTime
	}
	return nil
}

func (x *CreateDeliveryAssignmentRequest) GetEstimatedDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return nil
}

func (x *CreateDeliveryAssignmentRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// GetDeliveryAssignmentRequest retrieves a delivery assignment
type GetDeliveryAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryAssignmentRequest) Reset() {
	*x = GetDeliveryAssignmentRequest{}
	mi := &file_proto_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryAssignmentRequest) ProtoMessage() {}

func (x *GetDeliveryAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateDeliveryStatusRequest updates delivery status
type UpdateDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=delivery.DeliveryStatus" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_proto_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDeliveryStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_UNSPECIFIED
}

func (x *UpdateDeliveryStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// ListDeliveryAssignmentsRequest lists delivery assignments
type ListDeliveryAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=delivery.DeliveryStatus" json:"status,omitempty"`
	DriverId      string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryAssignmentsRequest) Reset() {
	*x = ListDeliveryAssignmentsRequest{}
	mi := &file_proto_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryAssignmentsRequest) ProtoMessage() {}

func (x *ListDeliveryAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveryAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *ListDeliveryAssignmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeliveryAssignmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDeliveryAssignmentsRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_UNSPECIFIED
}

func (x *ListDeliveryAssignmentsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

// ListDeliveryAssignmentsResponse returns paginated delivery assignments
type ListDeliveryAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*DeliveryAssignment  `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryAssignmentsResponse) Reset() {
	*x = ListDeliveryAssignmentsResponse{}
	mi := &file_proto_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryAssignmentsResponse) ProtoMessage() {}

func (x *ListDeliveryAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveryAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeliveryAssignmentsResponse) GetAssignments() []*DeliveryAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *ListDeliveryAssignmentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDeliveryAssignmentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeliveryAssignmentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// AssignDriverRequest assigns a driver to delivery
type AssignDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverRequest) Reset() {
	*x = AssignDriverRequest{}
	mi := &file_proto_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverRequest) ProtoMessage() {}

func (x *AssignDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverRequest.ProtoReflect.Descriptor instead.
func (*AssignDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *AssignDriverRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

// GetDeliveryMetricsRequest retrieves delivery metrics
type GetDeliveryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryMetricsRequest) Reset() {
	*x = GetDeliveryMetricsRequest{}
	mi := &file_proto_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryMetricsRequest) ProtoMessage() {}

func (x *GetDeliveryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeliveryMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetDeliveryMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetDeliveryMetricsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

// DeliveryMetrics contains aggregated delivery statistics
type DeliveryMetrics struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	TotalDeliveries            int32                  `protobuf:"varint,1,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	CompletedDeliveries        int32                  `protobuf:"varint,2,opt,name=completed_deliveries,json=completedDeliveries,proto3" json:"completed_deliveries,omitempty"`
	FailedDeliveries           int32                  `protobuf:"varint,3,opt,name=failed_deliveries,json=failedDeliveries,proto3" json:"failed_deliveries,omitempty"`
	CancelledDeliveries        int32                  `protobuf:"varint,4,opt,name=cancelled_deliveries,json=cancelledDeliveries,proto3" json:"cancelled_deliveries,omitempty"`
	AverageDeliveryTimeMinutes float64                `protobuf:"fixed64,5,opt,name=average_delivery_time_minutes,json=averageDeliveryTimeMinutes,proto3" json:"average_delivery_time_minutes,omitempty"`
	OnTimeDeliveryRate         float64                `protobuf:"fixed64,6,opt,name=on_time_delivery_rate,json=onTimeDeliveryRate,proto3" json:"on_time_delivery_rate,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DeliveryMetrics) Reset() {
	*x = DeliveryMetrics{}
	mi := &file_proto_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryMetrics) ProtoMessage() {}

func (x *DeliveryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryMetrics.ProtoReflect.Descriptor instead.
func (*DeliveryMetrics) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *DeliveryMetrics) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetCompletedDeliveries() int32 {
	if x != nil {
		return x.CompletedDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetFailedDeliveries() int32 {
	if x != nil {
		return x.FailedDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetCancelledDeliveries() int32 {
	if x != nil {
		return x.CancelledDeliveries
	}
	return 0
}

func (x *DeliveryMetrics) GetAverageDeliveryTimeMinutes() float64 {
	if x != nil {
		return x.AverageDeliveryTimeMinutes
	}
	return 0
}

func (x *DeliveryMetrics) GetOnTimeDeliveryRate() float64 {
	if x != nil {
		return x.OnTimeDeliveryRate
	}
	return 0
}

type DeleteDeliveryAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeliveryAssignmentRequest) Reset() {
	*x = DeleteDeliveryAssignmentRequest{}
	mi := &file_proto_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeliveryAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeliveryAssignmentRequest) ProtoMessage() {}

func (x *DeleteDeliveryAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeliveryAssignmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeliveryAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDeliveryAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_delivery_proto protoreflect.FileDescriptor

const file_proto_delivery_proto_rawDesc = "" +
	"\n" +
	"\x14proto/delivery.proto\x12\bdelivery\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc0\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\"\xce\x05\n" +
	"\x12DeliveryAssignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.delivery.DeliveryStatusR\x06status\x128\n" +
	"\x0epickup_address\x18\x05 \x01(\v2\x11.delivery.AddressR\rpickupAddress\x12<\n" +
	"\x10delivery_address\x18\x06 \x01(\v2\x11.delivery.AddressR\x0fdeliveryAddress\x12N\n" +
	"\x15scheduled_pickup_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x13scheduledPickupTime\x12R\n" +
	"\x17estimated_delivery_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15estimatedDeliveryTime\x12H\n" +
	"\x12actual_pickup_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10actualPickupTime\x12L\n" +
	"\x14actual_delivery_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12actualDeliveryTime\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xee\x02\n" +
	"\x1fCreateDeliveryAssignmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x128\n" +
	"\x0epickup_address\x18\x02 \x01(\v2\x11.delivery.AddressR\rpickupAddress\x12<\n" +
	"\x10delivery_address\x18\x03 \x01(\v2\x11.delivery.AddressR\x0fdeliveryAddress\x12N\n" +
	"\x15scheduled_pickup_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x13scheduledPickupTime\x12R\n" +
	"\x17estimated_delivery_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x15estimatedDeliveryTime\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\".\n" +
	"\x1cGetDeliveryAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.delivery.DeliveryStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"\xa0\x01\n" +
	"\x1eListDeliveryAssignmentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.delivery.DeliveryStatusR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\"\xb3\x01\n" +
	"\x1fListDeliveryAssignmentsResponse\x12>\n" +
	"\vassignments\x18\x01 \x03(\v2\x1c.delivery.DeliveryAssignmentR\vassignments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"B\n" +
	"\x13AssignDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"\xaa\x01\n" +
	"\x19GetDeliveryMetricsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\"\xc5\x02\n" +
	"\x0fDeliveryMetrics\x12)\n" +
	"\x10total_deliveries\x18\x01 \x01(\x05R\x0ftotalDeliveries\x121\n" +
	"\x14completed_deliveries\x18\x02 \x01(\x05R\x13completedDeliveries\x12+\n" +
	"\x11failed_deliveries\x18\x03 \x01(\x05R\x10failedDeliveries\x121\n" +
	"\x14cancelled_deliveries\x18\x04 \x01(\x05R\x13cancelledDeliveries\x12A\n" +
	"\x1daverage_delivery_time_minutes\x18\x05 \x01(\x01R\x1aaverageDeliveryTimeMinutes\x121\n" +
	"\x15on_time_delivery_rate\x18\x06 \x01(\x01R\x12onTimeDeliveryRate\"1\n" +
	"\x1fDeleteDeliveryAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*\x85\x01\n" +
	"\x0eDeliveryStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bASSIGNED\x10\x02\x12\r\n" +
	"\tPICKED_UP\x10\x03\x12\x0e\n" +
	"\n" +
	"IN_TRANSIT\x10\x04\x12\r\n" +
	"\tDELIVERED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\x12\r\n" +
	"\tCANCELLED\x10\a2\x88\a\n" +
	"\x0fDeliveryService\x12~\n" +
	"\x18CreateDeliveryAssignment\x12).delivery.CreateDeliveryAssignmentRequest\x1a\x1c.delivery.DeliveryAssignment\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/deliveries\x12z\n" +
	"\x15GetDeliveryAssignment\x12&.delivery.GetDeliveryAssignmentRequest\x1a\x1c.delivery.DeliveryAssignment\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/deliveries/{id}\x12\x82\x01\n" +
	"\x14UpdateDeliveryStatus\x12%.delivery.UpdateDeliveryStatusRequest\x1a\x1c.delivery.DeliveryAssignment\"%\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/v1/deliveries/{id}/status\x12\x86\x01\n" +
	"\x17ListDeliveryAssignments\x12(.delivery.ListDeliveryAssignmentsRequest\x1a).delivery.ListDeliveryAssignmentsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/deliveries\x12y\n" +
	"\fAssignDriver\x12\x1d.delivery.AssignDriverRequest\x1a\x1c.delivery.DeliveryAssignment\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/deliveries/{id}/assign-driver\x12t\n" +
	"\x12GetDeliveryMetrics\x12#.delivery.GetDeliveryMetricsRequest\x1a\x19.delivery.DeliveryMetrics\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/deliveries/metrics\x12z\n" +
	"\x18DeleteDeliveryAssignment\x12).delivery.DeleteDeliveryAssignmentRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/deliveries/{id}B7Z5github.com/mohamadchoker/order-delivery-service/protob\x06proto3"

var (
	file_proto_delivery_proto_rawDescOnce sync.Once
	file_proto_delivery_proto_rawDescData []byte
)

func file_proto_delivery_proto_rawDescGZIP() []byte {
	file_proto_delivery_proto_rawDescOnce.Do(func() {
		file_proto_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_delivery_proto_rawDesc), len(file_proto_delivery_proto_rawDesc)))
	})
	return file_proto_delivery_proto_rawDescData
}

var file_proto_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_delivery_proto_goTypes = []any{
	(DeliveryStatus)(0),                     // 0: delivery.DeliveryStatus
	(*Address)(nil),                         // 1: delivery.Address
	(*DeliveryAssignment)(nil),              // 2: delivery.DeliveryAssignment
	(*CreateDeliveryAssignmentRequest)(nil), // 3: delivery.CreateDeliveryAssignmentRequest
	(*GetDeliveryAssignmentRequest)(nil),    // 4: delivery.GetDeliveryAssignmentRequest
	(*UpdateDeliveryStatusRequest)(nil),     // 5: delivery.UpdateDeliveryStatusRequest
	(*ListDeliveryAssignmentsRequest)(nil),  // 6: delivery.ListDeliveryAssignmentsRequest
	(*ListDeliveryAssignmentsResponse)(nil), // 7: delivery.ListDeliveryAssignmentsResponse
	(*AssignDriverRequest)(nil),             // 8: delivery.AssignDriverRequest
	(*GetDeliveryMetricsRequest)(nil),       // 9: delivery.GetDeliveryMetricsRequest
	(*DeliveryMetrics)(nil),                 // 10: delivery.DeliveryMetrics
	(*DeleteDeliveryAssignmentRequest)(nil), // 11: delivery.DeleteDeliveryAssignmentRequest
	(*timestamppb.Timestamp)(nil),           // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 13: google.protobuf.Empty
}
var file_proto_delivery_proto_depIdxs = []int32{
	0,  // 0: delivery.DeliveryAssignment.status:type_name -> delivery.DeliveryStatus
	1,  // 1: delivery.DeliveryAssignment.pickup_address:type_name -> delivery.Address
	1,  // 2: delivery.DeliveryAssignment.delivery_address:type_name -> delivery.Address
	12, // 3: delivery.DeliveryAssignment.scheduled_pickup_time:type_name -> google.protobuf.Timestamp
	12, // 4: delivery.DeliveryAssignment.estimated_delivery_time:type_name -> google.protobuf.Timestamp
	12, // 5: delivery.DeliveryAssignment.actual_pickup_time:type_name -> google.protobuf.Timestamp
	12, // 6: delivery.DeliveryAssignment.actual_delivery_time:type_name -> google.protobuf.Timestamp
	12, // 7: delivery.DeliveryAssignment.created_at:type_name -> google.protobuf.Timestamp
	12, // 8: delivery.DeliveryAssignment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 9: delivery.CreateDeliveryAssignmentRequest.pickup_address:type_name -> delivery.Address
	1,  // 10: delivery.CreateDeliveryAssignmentRequest.delivery_address:type_name -> delivery.Address
	12, // 11: delivery.CreateDeliveryAssignmentRequest.scheduled_pickup_time:type_name -> google.protobuf.Timestamp
	12, // 12: delivery.CreateDeliveryAssignmentRequest.estimated_delivery_time:type_name -> google.protobuf.Timestamp
	0,  // 13: delivery.UpdateDeliveryStatusRequest.status:type_name -> delivery.DeliveryStatus
	0,  // 14: delivery.ListDeliveryAssignmentsRequest.status:type_name -> delivery.DeliveryStatus
	2,  // 15: delivery.ListDeliveryAssignmentsResponse.assignments:type_name -> delivery.DeliveryAssignment
	12, // 16: delivery.GetDeliveryMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 17: delivery.GetDeliveryMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	3,  // 18: delivery.DeliveryService.CreateDeliveryAssignment:input_type -> delivery.CreateDeliveryAssignmentRequest
	4,  // 19: delivery.DeliveryService.GetDeliveryAssignment:input_type -> delivery.GetDeliveryAssignmentRequest
	5,  // 20: delivery.DeliveryService.UpdateDeliveryStatus:input_type -> delivery.UpdateDeliveryStatusRequest
	6,  // 21: delivery.DeliveryService.ListDeliveryAssignments:input_type -> delivery.ListDeliveryAssignmentsRequest
	8,  // 22: delivery.DeliveryService.AssignDriver:input_type -> delivery.AssignDriverRequest
	9,  // 23: delivery.DeliveryService.GetDeliveryMetrics:input_type -> delivery.GetDeliveryMetricsRequest
	11, // 24: delivery.DeliveryService.DeleteDeliveryAssignment:input_type -> delivery.DeleteDeliveryAssignmentRequest
	2,  // 25: delivery.DeliveryService.CreateDeliveryAssignment:output_type -> delivery.DeliveryAssignment
	2,  // 26: delivery.DeliveryService.GetDeliveryAssignment:output_type -> delivery.DeliveryAssignment
	2,  // 27: delivery.DeliveryService.UpdateDeliveryStatus:output_type -> delivery.DeliveryAssignment
	7,  // 28: delivery.DeliveryService.ListDeliveryAssignments:output_type -> delivery.ListDeliveryAssignmentsResponse
	2,  // 29: delivery.DeliveryService.AssignDriver:output_type -> delivery.DeliveryAssignment
	10, // 30: delivery.DeliveryService.GetDeliveryMetrics:output_type -> delivery.DeliveryMetrics
	13, // 31: delivery.DeliveryService.DeleteDeliveryAssignment:output_type -> google.protobuf.Empty
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_delivery_proto_init() }
func file_proto_delivery_proto_init() {
	if File_proto_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_delivery_proto_rawDesc), len(file_proto_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_delivery_proto_goTypes,
		DependencyIndexes: file_proto_delivery_proto_depIdxs,
		EnumInfos:         file_proto_delivery_proto_enumTypes,
		MessageInfos:      file_proto_delivery_proto_msgTypes,
	}.Build()
	File_proto_delivery_proto = out.File
	file_proto_delivery_proto_goTypes = nil
	file_proto_delivery_proto_depIdxs = nil
}
